# Generated by Django 3.0.4 on 2020-03-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log_app', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Write text here',
            new_name='text',
        ),
    ]
